# Generated by Django 2.1.2 on 2018-10-01 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.TextField(verbose_name='object ID')),
                ('comment', models.CharField(max_length=300)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_comentariomodel', to='contenttypes.ContentType', verbose_name='content type')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='site',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
