# Generated by Django 2.0.6 on 2018-06-21 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_auto_20180621_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
