# Generated by Django 2.0.6 on 2018-08-01 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0004_aluno_em_turma_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_em_turma',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
