# Generated by Django 2.0.6 on 2018-08-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0006_auto_20180803_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_em_turma',
            name='codigo_turma',
            field=models.CharField(max_length=5),
        ),
    ]
