# Generated by Django 2.0.6 on 2018-08-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0007_auto_20180803_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno_em_turma',
            name='codigo_turma',
        ),
        migrations.AddField(
            model_name='aluno_em_turma',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='atividades.Turma'),
            preserve_default=False,
        ),
    ]
