# Generated by Django 2.0.6 on 2018-08-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0009_atividade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='code',
        ),
    ]
