# Generated by Django 2.0.6 on 2018-09-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0010_remove_atividade_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='disciplina',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
